#ifndef _RESOURCEMANAGEMENT_H_
#define _RESOURCEMANAGEMENT_H_

#include <map>
#include "BaseObject.h"
#include "DirectXGame.h"


enum EOTexture
{
	BACKGROUND_TEXTURE,
	BEGINBACKGROUND_TEXTURE,
	ABOUTBACKGROUND_TEXTURE,
	SETTINGBACKGROUND_TEXTURE,

	SOUNDLABEL_TEXTURE,
	SOUNDOPTION_TEXTURE,
	VOLUME_TEXTURE,

	BAR_TEXTURE,
	BLOCK_TEXTURE,
	BRICK_TEXTURE,
	BULLET_TEXTURE,
	CARNIVOROUSFLOWER_TEXTURE,

	CLOUD_TEXTURE,
	COIN_TEXTURE,
	ENEMY_TEXTURE,
	EXPLOREDBRICK_TEXTURE,
	FENCE_TEXTURE,

	FIREWORKS_TEXTURE,
	FLAGPOLE_TEXTURE,
	FLOWER_TEXTURE,
	GAMEOVERSCREEN_TEXTURE,
	GRASS_TEXTURE,

	HEIGHTMARIO_TEXTURE,
	HORIZONTALPIPE_TEXTURE,
	LAMP_TEXTURE,
	LAND_TEXTURE,
	MACHINEBULLET_TEXTURE,
	MACHINE_TEXTURE,
	MARIOICON_TEXTURE,

	MOUNTAIN_TEXTURE,
	MUSHROOM_TEXTURE,
	NUMBER_TEXTURE,
	PAUSEMENU_TEXTURE,
	PIPE_TEXTURE,

	SECRETBLOCK_TEXTURE,
	SIGN_TEXTURE,
	SMALLMARIO_TEXTURE,
	SPRING_TEXTURE,
	STAR_TEXTURE,

	STARTMENU_TEXTURE,
	SUPERMATIO_TEXTURE,
	TOWER_TEXTURE,
	TREE_TEXTURE,
	TREE2_TEXTURE,

	TURTLE_TEXTURE,
	TURTLE2_TEXTURE,
	WAITSCREEN_TEXTURE,
	WORLD_TEXTURE
};


class TextureManagement
{
private:
	map<EOTexture, DXTexture *> _ListTexture;
	
	static TextureManagement _instance;
	TextureManagement() { };
public:
	static TextureManagement* GetInstance()
	{
		return &_instance;
	};

	bool Add(LPDIRECT3DDEVICE9 d3dDevice, EOTexture type, char *path);
	bool Add(LPDIRECT3DDEVICE9 d3dDevice, EOTexture type, char *path, int nHor, int nVer);
	void AddAll(LPDIRECT3DDEVICE9 d3dDevice);
	DXTexture* Get(EOTexture name);
	EOTexture Get(DXTexture *);
};

#endif